---
- name: SSH hardening
  ansible.builtin.import_tasks: ssh.yml

- name: Ufw firewall
  ansible.builtin.import_tasks: ufw.yml

- name: Fail2ban
  ansible.builtin.import_tasks: fail2ban.yml

- name: Unattended upgrades
  ansible.builtin.import_tasks: unattended-upgrades.yml
